INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 0, 'Erick', 630021372 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 1, 'Gretchen', NULL );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 2, 'Robbie', 1835413374 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 3, 'Heath', NULL );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 4, 'Brandie', 1982395070 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 5, 'Fiona', 489965424 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 6, 'Randal', NULL );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 7, 'Kerican', 1595919047 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 8, 'Roberta', 1189181216 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 9, 'Cornelius', 1485318616 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 10, 'Lillian', 810716193 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 11, 'Geoffrey', 876785565 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 12, 'Moses', 1121290047 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 13, 'Arlene', 1206768426 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 14, 'Sheldon', 1711192608 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 15, 'Andre', 1250420388 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 16, 'Rex', 1274168422 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 17, 'Donna Anna', 328964149 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 18, 'Arnold', 1349478758 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 19, 'Bobbi', 1324227872 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 20, 'Frances', 1573760487 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 21, 'Luzican', 1802512063 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 22, 'Ruth', 1160090072 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 23, 'CreazyNuts', NULL );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 24, 'Damien', 1773322850 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 25, 'Laska', 70359707 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 26, 'Morgan', 1605025127 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 27, 'Guadalupe', 1190581120 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 28, 'Angela', 275012516 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 29, 'Jesse', 108721130 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 30, 'Herman', 1202535585 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 31, 'Loretta', 988508620 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 32, 'Deanadiablo', 825857095 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 33, 'Bridgett', 1695099879 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 34, 'mays', 1251488170 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 35, 'Kellie', 1556039312 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 36, 'Whitney', 899121869 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 37, 'Dwayne', 362450710 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 38, 'Jayson', 1616253156 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 39, 'Tim', 1209915257 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 40, 'Darla', 323232 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 41, 'Ron', 346277032 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 42, 'Judith', 1943164431 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 43, 'Luz', 61500489 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 44, 'Regina', 1333115794 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 45, 'Rudy', 1048738717 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 46, 'Jasmine', 523370305 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 47, 'Dustin', 989082393 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 48, 'Kirsten', 1973685784 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 49, 'Wesley', 707442196 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 50, 'TurkKurt', 872346679 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 51, 'Cassandra', 1514087666 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 52, 'Caroline', 2124079039 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 53, 'Crystal', 2039344977 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 54, 'Darren', 1227529523 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 55, 'Desiree', 382219873 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 56, 'Onixx', 796614524 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 57, 'Bobby', 606581965 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 58, 'Chanda', 1600583015 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 59, 'Anne', 1390432218 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 60, 'Marty', 1982558448 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 61, 'Darcy', 79084126 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 62, 'Lonnie', 2033184900 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 63, 'Kelley', 9136978305 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 64, 'Dena', 1972648401 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 65, 'Damion', 835121724 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 66, 'Owen', 230898064 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 67, 'Marcos', 1930974551 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 68, 'Keri', 844146985 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 69, 'Colleen', 803272158 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 70, 'Betsy', 85494807 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 71, 'Casey', 1874554653 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 72, 'Kisha', 725692328 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 73, 'Nina', 9136978301 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 74, 'Deana', 1596812764 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 75, 'Katie', 1399883845 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 76, 'Bennie', NULL );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 77, 'Rusty', 465458355 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 78, 'Rose', 4314527 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 79, 'Heidi', 9136978302 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 80, 'Veronica', 34723121 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 81, 'Joey', 45523759 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 82, 'Christie', 840085950 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 83, 'NULL', 1206486192 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 84, 'Nelson', 2085357282 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 85, 'Priscilla', 1141423039 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 86, 'Jill', 1821302470 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 87, 'Constance', 1201521543 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 88, 'Barry', 1940765931 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 89, 'KurtBlur', NULL );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 90, 'mayis', 1160914777 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 91, 'Sheryl', 915583316 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 92, 'Carmen', 1047721460 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 93, 'Allyson', 840977550 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 94, 'Rocky', 1008451641 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 95, 'Rosa', 374544265 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 96, 'Monique', 1525371301 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 97, 'Martin', 694451993 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 98, 'igor', 317815296 );
INSERT INTO suppliers ( supplier_id, supplier_name, phone_supplier ) VALUES ( 99, 'Yegor', 1521969040 );

INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 100, 'Abel', 1570126088 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 101, 'Erick', 1935844031 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 102, 'Janice', 1066918394 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 103, 'Gretchen', 2117154592 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 104, 'Lawanda', 1840659868 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 105, 'Robbie', 2120470093 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 106, 'Carla', 489965424 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 107, 'Heath', 160618522 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 108, 'Kendra', 1595919047 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 109, 'Brandie', 2039214544 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 110, 'Rose', 65526659 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 111, 'Ernest', 1485318616 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 112, 'Randal', 1828992267 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 113, 'Ismael', 121863560 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 114, 'Keri', 876785565 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 115, 'Cameron', 756749168 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 116, 'Roberta', 2133925812 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 118, 'Colby', 1206768426 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 119, 'Cornelius', 1022169017 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 120, 'Teddy', 106110341 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 121, 'Lillian', 1250420388 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 122, 'Dianna', 1828030354 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 123, 'Geoffrey', 491073319 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 124, 'Melissa', 328964149 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 125, 'Moses', 2070007347 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 126, 'Franklin', 499559765 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 127, 'Arlene', 1324227872 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 128, 'Kathleen', 1307592918 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 129, 'Sheldon', 531757751 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 130, 'Ivan', 1802512063 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 131, 'Andre', 1479606320 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 132, 'Joni', 1712955679 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 133, 'Rex', 265695738 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 134, 'Dwight', 231014531 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 135, 'Lucas', 70359707 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 136, 'Arnold', 2002877782 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 137, 'Kristen', 573006457 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 138, 'Bobbi', 1190581120 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 139, 'Carl', 488052483 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 140, 'Frances', 306801119 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 141, 'Elena', 108721130 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 142, 'Luz', 281161585 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 143, 'Jami', 124394731 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 144, 'Ruth', 988508620 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 145, 'Noah', 1004920843 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 146, 'Emma', 543558809 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 147, 'Damien', 1695099879 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 148, 'Caroline', 1657697649 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 149, 'Elisabeth', 741511677 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 150, 'Morgan', 1556039312 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 151, 'Clifford', 1899249900 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 152, 'Guadalupe', 907479117 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 153, 'Sophia', 362450710 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 154, 'Angela', 335617623 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 155, 'Byron', 374391246 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 156, 'Jesse', 1209915257 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 157, 'Paige', 208987943 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 158, 'Herman', 346277032 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 159, 'Clarissa', 1361490460 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 160, 'Loretta', 1133811621 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 161, 'Austin', 61500489 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 162, 'Deanas', 1195502579 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 163, 'William', 1282944731 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 164, 'Bridgett', 1048738717 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 165, 'Tamiko', 1944105894 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 166, 'Irma', 87974585 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 167, 'Kellie', 989082393 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 168, 'Alex', 847327837 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 169, 'Whitney', 1718410612 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 170, 'Marc', 707442196 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 171, 'Dwayne', 1420141612 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 172, 'Theodore', 1573088622 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 173, 'Jayson', 1514087666 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 174, 'Lauren', 1141365695 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 175, 'Tim', 2074068 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 176, 'Omar', 2039344977 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 177, 'Darla', 773339441 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 178, 'Melisa', 1352262686 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 179, 'Ron', 382219873 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 180, 'Heidi', 1055662347 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 181, 'Judith', 1954110780 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 182, 'Wallace', 606581965 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 183, 'Luz', 1589777239 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 184, 'Cari', 579416414 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 185, 'Regina', 1390432218 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 186, 'Latanya', 1746914044 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 187, 'Rudy', 1142351084 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 188, 'Lewis', 79084126 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 189, 'Jasmine', 1325399101 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 190, 'Laura', 372966688 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 191, 'Dustin', 232960925 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 192, 'Julian', 1254748079 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 193, 'Kirsten', 835121724 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 194, 'Rickey', 1859548706 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 195, 'Wesley', 1130472073 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 196, 'Brent', 1930974551 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 197, 'Kurt Nansen', 1898227307 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 198, 'Sonya', 660422257 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 199, 'Cassandra', 803272158 );
INSERT INTO customers ( customer_id, customer_name, customer_phone ) VALUES ( 200, 'Bobbie', 888995136 );

INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 0,  'Cheezer', 'yellow cheezer. ', 'm' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 1,  'Rapzapinex', 'Mike like sports. Mike like sports. ', 'cct' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 2,  'Lombanamantor', 'Mike loves flowers. ', 'vjc' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 3,  'Klibanollover', 'Mike like swimming. Rudi watches football. ', 'pcs' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 4,  'Admunover', 'Rudi like swimming. Mike like sports. ', 'dws' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 5,  'Undudplazz', 'Mike watches football. Rudi watches football. ', 'zny' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 6,  'Aderplar', 'Mike loves flowers. Mike watches football. ', 'omu' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 7,  'Vartanentor', 'Mike loves flowers. Mike watches football. ', 'khe' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 8,  'Happickamex', 'Mike like swimming. Rudi loves flowers. ', 'ddi' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 9,  'Rerobepicator', 'Mike like sports. Rudi watches football. ', 'ogr' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 10,  'Thrukilanicator', 'Mike loves flowers. Mike watches football. ', 'clj' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 11,  'Parerupax', 'Rudi watches football. Rudi loves flowers. ', 'dtm' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 12,  'Tipdudower', 'I watches football. ', 'glj' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 13,  'Monmunazz', 'I watches football. Mike watches football. ', 'nmi' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 14,  'Varwerentor', 'pcs', 'jhx' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 15,  'Cipglibupicator', 'I loves flowers. Rudi watches football. ', 'sof' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 16,  'Monwerazz', 'Mike loves flowers. Mike loves flowers. ', 'sxg' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 17,  'Grorobopicator', 'pcs', 'hsy' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 18,  'Emhupackor', 'Mike like swimming. Mike loves flowers. ', 'hre' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 19,  'Glamuromunplor', 'I like sports. Mike watches football. ', 'eqq' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 20,  'Tipfropanover', 'I loves flowers. ', 'hye' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 21,  'Klikilplistor', 'Mike watches football. Rudi watches football. ', 'kea' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 22,  'Inpickackistor', 'Rudi watches football. I like sports. ', 'dib' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 23,  'Doppebonistor', 'Mike loves flowers. Mike like swimming. ', 'yer' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 24,  'Dopjubax', 'Rudi watches football. Mike watches football. ', 'vjv' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 25,  'Dopnipazz', 'I watches football. Rudi loves flowers. ', 'pcs' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 26,  'Qwicadplentor', 'Mike loves flowers. Rudi like swimming. ', 'pcs' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 27,  'Unerepan', 'pcs', 'dal' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 28,  'Embanplex', 'Mike loves flowers. ', 'pjv' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 29,  'Revenplazz', 'Mike like swimming. I loves flowers. ', 'ald' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 30,  'Cipnipommin', 'Mike loves flowers. Rudi like sports. ', 'vgj' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 31,  'Zeezapupin', 'I loves flowers. Mike watches football. ', 'kyy' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 32,  'Winnipplover', 'Mike loves flowers. Rudi loves flowers. ', 'dth' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 33,  'Supbanupower', 'Mike watches football. Rudi loves flowers. ', 'ruf' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 34,  'Trupebentor', 'Rudi like sports. Mike watches football. ', 'dpo' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 35,  'Trucadistor', 'Rudi loves flowers. Mike watches football. ', 'chq' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 36,  'Upmunackex', 'I like sports. I watches football. ', 'cdl' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 37,  'Varcadanor', 'Mike like sports. ', 'tyx' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 38,  'Winsapopex', 'Rudi loves flowers. Rudi watches football. ', 'kg' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 39,  'Varjubinazz', 'Rudi watches football. I watches football. ', 'sol' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 40,  'Lomcadopazz', 'Rudi loves flowers. ', 'cgi' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 41,  'Qwirobar', 'Mike watches football. Rudi watches football. ', 'jbq' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 42,  'Uperplentor', 'Rudi watches football. I watches football. ', 'cuo' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 43,  'Raptumupazz', 'I watches football. Mike loves flowers. ', 'bfo' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 44,  'Qwitinanazz', 'Rudi like sports. Rudi watches football. ', 'kg' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 45,  'Grocadplor', 'I loves flowers. Rudi watches football. ', 'drm' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 46,  'Winweranistor', 'Mike watches football. Mike loves flowers. ', 'cct' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 47,  'Barglibazz', 'Mike loves flowers. Rudi like sports. ', 'igd' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 48,  'Qwijubupin', 'Mike like sports. Rudi watches football. ', 'zuy' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 49,  'Winmunplantor', 'Rudi like swimming. Rudi like swimming. ', 'utr' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 50,  'Trudimollentor', 'I watches football. Mike watches football. ', 'jsz' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 51,  'Parmunentor', 'Mike loves flowers. I watches football. ', 'dqt' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 52,  'Adnipupex', 'I like sports. I like sports. ', 'xhh' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 53,  'Barmunplicator', 'Mike watches football. Rudi like sports. ', 'fmb' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 54,  'Trubanicax', 'I loves flowers. Rudi watches football. ', 'kg' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 55,  'Varzapan', 'Mike like sports. Mike loves flowers. ', 'die' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 56,  'Pardudar', 'I watches football. I watches football. ', 'rzy' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 57,  'Unvenamistor', 'Rudi like swimming. ', 'jir' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 58,  'Winmunover', 'Mike watches football. Mike like sports. ', 'fbf' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 59,  'Parnipover', 'I loves flowers. Rudi watches football. ', 'bae' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 60,  'Barnipor', 'I like swimming. Mike loves flowers. ', 'pcs' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 61,  'Barzapplin', 'I watches football. I like sports. ', 'ker' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 62,  'Rapglibplax', 'Mike loves flowers. Mike watches football. ', 'sfg' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 63,  'Rapjubupistor', 'Mike watches football. Rudi loves flowers. ', 'kmo' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 64,  'Monmunepin', 'Mike like sports. Mike like sports. ', 'mwa' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 65,  'Enddimaquex', 'Rudi loves flowers. Mike watches football. ', 'pcs' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 66,  'Lompickentor', 'Mike loves flowers. I watches football. ', 'ujj' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 67,  'Superollentor', 'pcs', 'wzf' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 68,  'Barkilican', 'Mike watches football. Rudi like sports. ', 'dnl' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 69,  'Uphupupicator', 'Mike watches football. Mike watches football. ', 'rok' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 70,  'Unmunadin', 'I watches football. ', 'owb' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 71,  'Rapvenanower', 'Mike loves flowers. I watches football. ', 'oxu' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 72,  'Gromunplor', 'Rudi watches football. Rudi watches football. ', 'otg' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 73,  'Hapsapackex', 'pcs', 'ifa' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 74,  'Doperover', 'pcs', 'hoq' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 75,  'Zeebanax', 'Mike watches football. Rudi watches football. ', 'jmn' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 76,  'Hapnipedar', 'I watches football. Rudi loves flowers. ', 'scp' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 77,  'Klihupupover', 'I loves flowers. Rudi watches football. ', 'kmr' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 78,  'Barhupplin', 'I like swimming. Mike like swimming. ', 'cky' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 79,  'Inzapower', 'Rudi watches football. Rudi watches football. ', 'kbg' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 80,  'Cipfropistor', 'Mike watches football. Mike watches football. ', 'osb' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 81,  'Trukilupentor', 'Mike watches football. Rudi watches football. ', 'wyp' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 82,  'Pardimplistor', 'Rudi watches football. I like sports. ', 'jlb' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 83,  'Hapfropplistor', 'Rudi like swimming. Rudi watches football. ', 'ijp' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 84,  'Bartinicower', 'Mike loves flowers. Rudi watches football. ', 'bmu' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 85,  'Bardudedazz', 'Mike watches football. I watches football. ', 'eiv' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 86,  'Inzapamistor', 'Mike watches football. Mike like swimming. ', 'ryh' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 87,  'Hapzapplentor', 'I like swimming. Mike loves flowers. ', 'hbg' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 88,  'Dopjubexin', 'Rudi watches football. ', 'cmt' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 89,  'Froweronex', 'Mike loves flowers. Rudi watches football. ', 'hdw' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 90,  'Revenaquistor', 'Mike like swimming. Rudi watches football. ', 'tws' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 91,  'Reglibedistor', 'Rudi watches football. Mike watches football. ', 'nrg' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 92,  'Lomcadazz', 'pcs', 'tpo' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 93,  'Grovenepex', 'Rudi watches football. Mike loves flowers. ', 'wnr' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 94,  'Uprobupar', 'Rudi like sports. I watches football. ', 'yvp' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 95,  'Lomtinor', 'I watches football. Mike like swimming. ', 'sob' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 96,  'Barweregar', 'Rudi like sports. I like swimming. ', 'naw' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 97,  'Barrobplentor', 'pcs', 'est' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 98,  'Klirobupistor', 'I watches football. Mike watches football. ', 'pcs' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 99,  'Winkilepax', 'Rudi like swimming. Mike like sports. ', 'ryv' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 100,  'Zeenipommistor', 'Mike like sports. I watches football. ', 'cwo' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 101,  'Uncadover', 'Rudi watches football. Mike watches football. ', 'pvx' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 102,  'Lomdimopazz', 'Rudi watches football. Rudi loves flowers. ', 'jsw' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 103,  'Cipvenplicator', 'Rudi loves flowers. Mike watches football. ', 'xyg' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 104,  'Lomkilentor', 'pcs', 'bzo' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 105,  'Moncadackar', 'Mike like sports. ', 'evl' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 106,  'Cipvenistorf', 'Rudi like swimming. Mike watches football. ', 'grn' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 107,  'Lomwerplistor', 'Mike watches football. Mike watches football. ', 'yrk' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 108,  'Hapglibicover', 'I watches football. Rudi watches football. ', 'xtl' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 109,  'Pardudplor', 'Mike like sports. Rudi like sports. ', 'flb' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 110,  'Zeecadupistor', 'Mike like swimming. Rudi like sports. ', 'cnt' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 111,  'Adericar', 'Mike loves flowers. Rudi watches football. ', 'pcs' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 112,  'Truvenplistor', 'Mike watches football. ', 'ijk' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 113,  'Growerpazz', 'Mike watches football. Rudi loves flowers. ', 'jhh' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 114,  'Hapdimupicator', 'Mike like swimming. Rudi watches football. ', 'wtx' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 115,  'Ciphupupower', 'Mike watches football. ', 'nee' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 116,  'Hapvenor', 'Mike watches football. Rudi watches football. ', 'lhn' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 117,  'Qwivenopax', 'I watches football. Rudi loves flowers. ', 'ijg' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 118,  'Barjubover', 'Mike loves flowers. Mike watches football. ', 'iul' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 119,  'Ciperar', 'pcs', 'lba' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 120,  'Klimunplor', 'Mike like swimming. Rudi watches football. ', 'pcs' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 121,  'Zeezapplazz', 'Rudi watches football. Mike watches football. ', 'nyz' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 122,  'Unfropupar', 'I loves flowers. Rudi like swimming. ', 'sdv' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 123,  'Cipvenonicator', 'Mike watches football. Mike like swimming. ', 'ncr' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 124,  'Lomnipplicator', 'I watches football. ', 'ogo' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 125,  'Qwisipistor', 'Mike watches football. Rudi like sports. ', 'its' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 126,  'Cipwerpamax', 'Mike like swimming. ', 'htc' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 127,  'Rekilicex', 'Rudi watches football. Rudi watches football. ', 'tei' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 128,  'Supdimicin', 'I loves flowers. Rudi like swimming. ', 'pcs' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 129,  'Rehupewazz', 'Mike watches football. ', 'zui' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 130,  'Klierplazz', 'Mike loves flowers. Rudi watches football. ', 'vet' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 131,  'Tipcadupantor', 'I loves flowers. I like swimming. ', 'oqp' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 132,  'Barsapexor', 'Rudi watches football. Mike like sports. ', 'tmg' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 133,  'Unnipazz', 'Mike like sports. Rudi like sports. ', 'ftl' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 134,  'Hapzapaman', 'Mike loves flowers. Mike watches football. ', 'nxo' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 135,  'Winvenonicator', 'Mike watches football. Mike like swimming. ', 'hmm' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 136,  'Qwihupover', 'pcs', 'olz' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 137,  'Rehupepicator', 'Rudi watches football. Rudi watches football. ', 'jey' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 138,  'Monhupplar', 'pcs', 'asq' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 139,  'Varwerar', 'Rudi loves flowers. I watches football. ', 'ohh' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 140,  'Lomsipplin', 'I watches football. Rudi watches football. ', 'lmx' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 141,  'Zeepickistor', 'I watches football. I watches football. ', 'iyw' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 142,  'Lomhupepin', 'I watches football. Mike watches football. ', 'vwv' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 143,  'Varcadegover', 'Mike loves flowers. ', 'riy' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 144,  'Endmunepistor', 'Mike watches football. Rudi loves flowers. ', 'dpg' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 145,  'Tipsapplazz', 'I watches football. Mike watches football. ', 'igx' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 146,  'Trubanegicator', 'I watches football. Mike like sports. ', 'pcs' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 147,  'Rezapanistor', 'Mike watches football. Mike watches football. ', 'eyu' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 148,  'Klifropar', 'Mike like sports. I loves flowers. ', 'qbq' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 149,  'Parwerollex', 'Rudi like swimming. Mike loves flowers. ', 'ijx' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 150,  'Emkililor', 'Rudi watches football. Mike watches football. ', 'pcs' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 151,  'Haptumor', 'Mike watches football. Rudi watches football. ', 'mso' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 152,  'Barvenollistor', 'Mike loves flowers. Rudi loves flowers. ', 'vih' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 153,  'Trusipupex', 'Rudi like sports. Mike watches football. ', 'xla' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 154,  'Reglibomman', 'Rudi like swimming. I watches football. ', 'uex' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 155,  'Rekilplover', 'I like sports. ', 'mez' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 156,  'Barjubplentor', 'Rudi watches football. ', 'tki' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 157,  'Inglibar', 'Mike watches football. Rudi watches football. ', 'oes' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 158,  'Emjubackentor', 'Mike watches football. I loves flowers. ', 'gmq' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 159,  'Adfropedex', 'pcs', 'rbi' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 160,  'Ciptumentor', 'I watches football. Rudi watches football. ', 'bpn' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 161,  'Reglibopax', 'Rudi loves flowers. Mike watches football. ', 'swt' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 162,  'Qwisipplicator', 'Mike like sports. I like sports. ', 'kvr' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 163,  'Klidudplex', 'Rudi like sports. Mike watches football. ', 'pcs' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 164,  'Groquestplazz', 'I loves flowers. I watches football. ', 'ciw' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 165,  'Doppebollor', 'Mike watches football. Mike watches football. ', 'pcs' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 166,  'Klihupilentor', 'Mike watches football. Rudi watches football. ', 'fps' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 167,  'Kliwerpollazz', 'I like swimming. Rudi watches football. ', 'dir' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 168,  'Qwifropplor', 'Mike like sports. I like swimming. ', 'lpg' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 169,  'Froglibistor', 'Mike watches football. Rudi like swimming. ', 'mmo' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 170,  'Zeerobanistor', 'Rudi watches football. Rudi watches football. ', 'zfw' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 171,  'Wincadepar', 'Mike like swimming. Mike like swimming. ', 'jvc' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 172,  'Kliglibazz', 'Rudi like swimming. Rudi watches football. ', 'nfk' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 173,  'Cipmunedar', 'Rudi like swimming. Mike like swimming. ', 'ufx' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 174,  'Haptinar', 'Mike loves flowers. Rudi watches football. ', 'pcs' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 175,  'Haprobewistor', 'Mike like sports. I watches football. ', 'cro' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 176,  'Thrukilommentor', 'I like sports. ', 'vpg' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 177,  'Cipzapower', 'I watches football. Rudi watches football. ', 'oed' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 178,  'Inmunupazz', 'Rudi watches football. Rudi loves flowers. ', 'xnb' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 179,  'Klimunaquar', 'pcs', 'cxn' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 180,  'Rapfropommazz', 'Rudi watches football. Rudi like sports. ', 'tme' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 181,  'Cipzapistor', 'I like sports. Mike loves flowers. ', 'jds' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 182,  'Monvenistor', 'Rudi watches football. Mike loves flowers. ', 'nby' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 183,  'Cipcadanazz', 'Mike watches football. Rudi like sports. ', 'pcs' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 184,  'Mondimupar', 'I loves flowers. ', 'mvj' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 185,  'Adpebommicator', 'Mike watches football. ', 'lno' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 186,  'Adfropackax', 'Mike like sports. Mike loves flowers. ', 'pcs' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 187,  'Tipfropegicator', 'I watches football. Rudi loves flowers. ', 'sni' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 188,  'Barerplistor', 'Mike loves flowers. Mike watches football. ', 'vug' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 189,  'Parcadepar', 'Mike watches football. ', 'tzk' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 190,  'Varmunor', 'Rudi like swimming. Mike watches football. ', 'pcs' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 191,  'Varvenanicator', 'Rudi loves flowers. Mike watches football. ', 'nsf' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 192,  'Qwitanopistor', 'Mike like sports. Mike watches football. ', 'pcs' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 193,  'Monnipollover', 'pcs', 'iyh' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 194,  'Barcadopower', 'I like sports. Rudi loves flowers. ', 'pcs' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 195,  'Montinommex', 'I loves flowers. Mike like swimming. ', 'pcs' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 196,  'Enddimewin', 'Rudi watches football. Rudi watches football. ', 'xkl' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 197,  'Cipvenistorn', 'Mike loves flowers. Rudi loves flowers. ', 'blc' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 198,  'Lompebepazz', 'Mike loves flowers. Mike watches football. ', 'xmg' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 199,  'Qwihupopistor', 'pcs', 'gfb' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 200,  'Klifropicar', 'pcs', 'nzi' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 201,  'Barveninover', 'Mike like sports. I like sports. ', 'bbo' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 202,  'Parkilower', 'I like sports. Mike watches football. ', 'rus' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 203,  'Barpebepar', 'Mike like swimming. Rudi loves flowers. ', 'dfv' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 204,  'Zeerobplor', 'I like swimming. ', 'frz' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 205,  'Inbanupicator', 'I watches football. Rudi like swimming. ', 'poo' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 206,  'Tupnipar', 'Mike watches football. Rudi watches football. ', 'pcs' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 207,  'Doperamar', 'Mike like sports. Rudi like swimming. ', 'ntw' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 208,  'Lomzapupor', 'Mike loves flowers. I watches football. ', 'brg' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 209,  'Windimover', 'I like swimming. Rudi loves flowers. ', 'otr' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 210,  'Monmunollower', 'Mike watches football. Rudi watches football. ', 'tof' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 211,  'Dopwerpopistor', 'Rudi watches football. I watches football. ', 'wuq' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 212,  'Hapfropepistor', 'I loves flowers. Mike like swimming. ', 'gcc' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 213,  'Adzapupower', 'I like swimming. Rudi loves flowers. ', 'htm' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 214,  'Lomzapax', 'I watches football. Mike like sports. ', 'pcs' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 215,  'Incadopar', 'Mike watches football. Mike watches football. ', 'ite' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 216,  'Cipmunazz', 'pcs', 'olc' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 217,  'Winjubentor', 'Mike like sports. ', 'ilf' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 218,  'Upkilistor', 'Rudi loves flowers. Mike watches football. ', 'vtf' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 219,  'Endpickplover', 'Rudi watches football. Rudi watches football. ', 'fqy' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 220,  'Hapvenplax', 'Mike like sports. Mike watches football. ', 'igu' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 221,  'Cipmunommazz', 'Mike watches football. ', 'wny' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 222,  'Monbanplicator', 'Rudi like swimming. I like sports. ', 'cjh' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 223,  'Winerackicator', 'Rudi loves flowers. Mike loves flowers. ', 'njq' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 224,  'Surtinopex', 'Mike loves flowers. Mike watches football. ', 'pcs' );
INSERT INTO goods ( product_id, product_name, decription, unit_of_measure ) VALUES ( 225,  'Kliwerinin', 'Mike like sports. ', 'wwe' );

INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 0, '2014-08-14', 73, 47, 1568971868, 1568779460  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 1, '2002-01-03', 29, 95, 1972923321, 189533491  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 2, '2008-03-14', 90, 185, 1972693766, 1049914525  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 3, '2008-02-24', 0, 184, 1459337896, 991787865  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 4, '2004-02-26', 49, 67, 168336463, 963357709  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 5, '2000-09-21', 85, 30, 53286715, 1498325847  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 6, '2006-08-27', 98, 203, 1501631576, 596500746  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 7, '2013-03-06', 3, 32, 1728588967, 1632003450  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 8, '2019-05-10', 85, 123, 324768466, 470823982  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 9, '2014-03-19', 92, 163, 1985522668, 1976574038  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 10, '2000-02-14', 98, 223, 1640324086, 1902790313  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 11, '2003-01-20', 45, 145, 7260017, 476744810  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 12, '2019-04-10', 22, 175, 1581456746, 1898114751  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 13, '2003-03-11', 51, 15, 2053467021, 943745161  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 14, '2018-10-18', 7, 161, 1768772963, 843695732  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 15, '2011-01-30', 84, 31, 405193588, 2136170708  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 16, '2018-12-11', 74, 53, 700291788, 1893008549  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 17, '2018-03-21', 24, 28, 1613937925, 608057716  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 18, '2018-09-28', 94, 73, 602196366, 532200929  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 19, '2009-09-28', 55, 11, 494165778, 1274669583  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 20, '2007-12-11', 3, 108, 1734358422, 1099186895  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 21, '2018-04-12', 11, 33, 1630396588, 165801873  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 22, '2006-12-13', 69, 196, 1677993262, 86243530  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 23, '2003-03-09', 78, 21, 1917884299, 1466876474  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 24, '2005-11-18', 85, 297, 1125381688, 967944046  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 25, '2007-05-19', 37, 9, 110423163, 761394934  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 26, '2010-02-16', 5, 14, 744779427, 648204718  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 27, '2017-04-15', 27, 223, 1031252175, 269367491  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 28, '2002-04-27', 40, 87, 1946868932, 751065074  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 29, '2010-10-14', 94, 259, 1225068592, 1486741939  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 30, '2015-05-30', 35, 124, 1197720890, 434912118  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 31, '2011-09-01', 52, 124, 1227838943, 73244298  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 32, '2013-03-13', 99, 55, 1927677104, 415104292  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 33, '2000-11-04', 67, 82, 460661275, 498935743  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 34, '2003-02-19', 56, 37, 694380035, 82555530  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 35, '2015-03-27', 33, 73, 318109936, 1468971070  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 36, '2007-07-25', 47, 116, 1462095149, 1252362683  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 37, '2012-06-24', 79, 10, 2011001547, 1789824375  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 38, '2002-10-18', 4, 151, 1206401873, 1326126777  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 39, '2017-08-02', 17, 175, 627792922, 1397119401  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 40, '2013-11-24', 58, 187, 1746734257, 588080664  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 41, '2009-01-01', 16, 77, 720234895, 1509241678  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 42, '2016-02-08', 85, 76, 1550250572, 2145807159  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 43, '2000-02-05', 59, 72, 1323587780, 1021520387  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 44, '2000-02-06', 22, 175, 1539328698, 196740887  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 45, '2017-01-16', 23, 20, 122906805, 1842367865  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 46, '2010-06-18', 15, 205, 967088502, 1203667209  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 47, '2000-06-20', 66, 45, 1144668466, 1059163613  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 48, '2014-11-17', 96, 160, 1338638879, 1796074015  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 49, '2014-02-06', 62, 27, 1479375231, 392856049  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 50, '2002-11-03', 23, 95, 1857341064, 60786579  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 51, '2005-07-02', 68, 84, 1082593065, 395950841  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 52, '2009-08-20', 61, 202, 1070394266, 1904212747  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 53, '2001-07-04', 2, 78, 1567965386, 341700920  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 54, '2010-11-21', 60, 24, 1790854555, 2026931758  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 55, '2012-03-18', 73, 75, 933191022, 1244984258  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 56, '2011-07-17', 24, 84, 351096714, 16867573  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 57, '2019-02-05', 72, 160, 1412873036, 1232725101  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 58, '2004-02-05', 83, 34, 818892307, 12631373  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 59, '2005-06-25', 0, 115, 976955264, 1666640415  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 60, '2012-06-19', 68, 134, 1780113534, 634893277  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 61, '2003-10-21', 54, 9, 127746415, 1381442818  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 62, '2003-09-11', 79, 126, 1797931490, 1883762633  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 63, '2000-01-10', 1, 82, 937316866, 1276660525  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 64, '2000-03-19', 12, 145, 1103142222, 605067664  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 65, '2013-09-02', 82, 21, 653546485, 31980602  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 66, '2003-03-22', 10, 48, 1368650712, 716084195  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 67, '2009-09-22', 10, 21, 1538390760, 1653567925  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 68, '2003-07-24', 3, 53, 806239115, 2085866313  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 69, '2009-10-01', 84, 117, 534622188, 147904907  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 70, '2010-10-22', 93, 93, 1582068937, 177401065  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 71, '2002-07-13', 74, 62, 1453298028, 1791246849  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 72, '2019-06-23', 26, 133, 1728223736, 2121826990  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 73, '2002-08-09', 80, 10, 52276011, 1660330796  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 74, '2004-11-27', 55, 241, 964389720, 408947758  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 75, '2004-02-15', 3, 74, 35567368, 59518390  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 76, '2007-11-21', 22, 25, 530692572, 132337449  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 77, '2016-11-29', 12, 34, 92199078, 240102418  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 78, '2004-05-08', 14, 20, 318304442, 1739307635  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 79, '2008-02-17', 98, 24, 1682368263, 355163463  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 80, '2008-08-21', 5, 25, 230998572, 1733382920  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 81, '2018-12-30', 33, 1, 2104357928, 1638159421  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 82, '2004-08-30', 13, 45, 1450964961, 1785743576  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 83, '2010-06-01', 55, 134, 1054205715, 775423351  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 84, '2017-10-18', 5, 47, 1646299575, 257288376  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 85, '2007-09-29', 36, 21, 1359943517, 579620557  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 86, '2000-10-07', 46, 80, 1045904374, 314002045  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 87, '2005-06-04', 39, 01, 2013003625, 1977409622  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 88, '2011-11-06', 46, 221, 1480272103, 1148170339  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 89, '2002-04-04', 38, 102, 531445051, 915772016  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 90, '2013-02-07', 25, 20, 1158526306, 954873289  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 91, '2004-07-29', 79, 29, 1423899448, 1094177424  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 92, '2002-05-25', 78, 154, 1814664303, 1262093518  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 93, '2019-11-02', 26, 18, 210034349, 2082598915  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 94, '2013-01-18', 77, 200, 1445435769, 1855843670  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 95, '2011-09-22', 58, 4, 719646861, 1949414656  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 96, '2019-09-08', 34, 54, 370032389, 1189075075  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 97, '2019-03-30', 92, 23, 1879789358, 2083017240  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 98, '2004-02-19', 72, 41, 1657855889, 726544682  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 99, '2005-04-21', 53, 149, 1576521935, 617367922  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 100, '2007-06-29', 88, 75, 1332855981, 2006252469  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 101, '2007-04-04', 41, 40, 1475526775, 1051108177  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 102, '2009-04-07', 42, 154, 652890110, 438171772  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 103, '2017-07-26', 42, 166, 923975956, 2055427126  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 104, '2006-09-03', 16, 139, 816749515, 1551550654  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 105, '2005-10-24', 72, 147, 625805013, 405888837  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 106, '2008-11-11', 15, 82, 2002131450, 1028764227  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 107, '2001-01-10', 75, 132, 1468676666, 2046681317  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 108, '2010-01-30', 17, 21, 583585742, 1677015468  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 109, '2003-09-02', 46, 29, 1129149864, 1202571385  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 110, '2019-12-24', 56, 22, 1651044955, 500723504  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 111, '2012-09-26', 80, 120, 1251995926, 1475128607  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 112, '2012-08-10', 9, 81, 1948959755, 1360356849  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 113, '2005-07-23', 23, 63, 1615530885, 803456927  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 114, '2018-03-11', 16, 51, 1065924814, 1389949476  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 115, '2006-10-26', 26, 1, 2014545653, 210942681  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 116, '2010-02-25', 63, 27, 350223650, 1281255039  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 117, '2005-04-25', 90, 27, 1170466405, 1630827484  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 118, '2009-10-30', 52, 164, 52537222, 1456974401  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 119, '2002-05-02', 19, 102, 2139161008, 873794931  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 120, '2008-07-29', 2, 25, 1493627754, 969516178  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 121, '2002-09-26', 29, 23, 1665335305, 73547950  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 122, '2006-02-28', 55, 72, 1211828255, 1571460024  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 123, '2010-12-03', 62, 145, 1300106213, 1313770295  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 124, '2014-05-07', 59, 217, 1582493152, 1703906672  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 125, '2009-11-22', 87, 215, 1529426426, 133682829  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 126, '2019-04-01', 48, 200, 18117348, 806355088  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 127, '2000-04-22', 93, 0, 143064376, 730139118  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 128, '2004-03-10', 90, 50, 328655688, 1691988182  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 129, '2007-03-07', 24, 111, 1601864216, 914002167  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 130, '2003-06-15', 4, 61, 609522754, 2002602724  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 131, '2004-11-06', 80, 105, 1156360894, 1107067131  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 132, '2010-12-24', 46, 43, 1735550386, 656622992  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 133, '2016-01-09', 81, 106, 1878046347, 339060348  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 134, '2011-02-09', 39, 24, 1953659833, 1566207444  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 135, '2002-03-13', 91, 28, 1142161149, 1258644918  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 136, '2011-10-04', 80, 153, 1297716045, 682432177  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 137, '2010-05-17', 66, 215, 297022109, 269154194  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 138, '2015-10-14', 32, 75, 723677584, 1912571404  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 139, '2010-07-14', 64, 66, 1551391347, 1556295070  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 140, '2013-12-24', 66, 24, 374411797, 2114574685  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 141, '2007-03-15', 40, 40, 1681660355, 861308392  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 142, '2004-02-03', 73, 59, 1655657807, 1785281507  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 143, '2008-11-06', 47, 165, 83999597, 1082653308  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 144, '2005-02-05', 70, 89, 215421192, 208136528  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 145, '2013-12-28', 61, 29, 100056478, 294753279  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 146, '2015-07-23', 53, 25, 189367376, 33100910  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 147, '2003-06-27', 98, 97, 1600106249, 71462164  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 148, '2004-07-01', 0, 82, 1502761709, 836595479  );
INSERT INTO purchases ( purchase_id, purchase_date, supplier_id, product_id, purchase_qnty, purchase_price ) VALUES ( 149, '2013-12-28', 62, 38, 242962476, 1090677734  );

INSERT INTO sales ( sale_id, sale_date, customer_id, product_id, sale_qnty, sale_price ) VALUES ( 100, '2002-01-03', 100, 38, 1948991452, 379250082  );
