# Form implementation generated from reading ui file 'ui_db_gui.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

# ui_db_gui.py

from PyQt6 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.list_tables = QtWidgets.QComboBox(parent=self.centralwidget)
        self.list_tables.setGeometry(QtCore.QRect(80, 20, 86, 26))
        self.list_tables.setObjectName("list_tables")
        self.Show_Button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Show_Button.setGeometry(QtCore.QRect(190, 20, 101, 26))
        self.Show_Button.setObjectName("Show_Button")
        self.data_here = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.data_here.setGeometry(QtCore.QRect(70, 140, 631, 361))
        self.data_here.setObjectName("data_here")
        self.data_here.setColumnCount(0)
        self.data_here.setRowCount(0)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(80, 60, 113, 26))
        self.lineEdit.setObjectName("lineEdit")
        self.Add_text_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Add_text_btn.setGeometry(QtCore.QRect(220, 60, 88, 26))
        self.Add_text_btn.setObjectName("Add_text_btn")
        self.Del_Button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Del_Button.setGeometry(QtCore.QRect(80, 110, 88, 26))
        self.Del_Button.setObjectName("Del_Button")
        self.plot_Button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.plot_Button.setGeometry(QtCore.QRect(560, 50, 88, 26))
        self.plot_Button.setObjectName("plot_Button")
        self.max_price_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.max_price_btn.setGeometry(QtCore.QRect(450, 50, 100, 26))
        self.max_price_btn.setObjectName("max_price_btn")
        self.sales_chart_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.sales_chart_btn.setGeometry(QtCore.QRect(550, 100, 150, 26))
        self.sales_chart_btn.setObjectName("sales_chart_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow_Petshop"))
        self.Show_Button.setText(_translate("MainWindow", "Show_Button"))
        self.Add_text_btn.setText(_translate("MainWindow", "Add_text"))
        self.Del_Button.setText(_translate("MainWindow", "Del_Button"))
        self.plot_Button.setText(_translate("MainWindow", "Plot_Button"))
        self.max_price_btn.setText(_translate("MainWindow", "MAX Цена"))
        self.sales_chart_btn.setText(_translate("MainWindow", "Диаграмма продаж"))
